// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBMNgAMcy0TVMr4VNnq_08DxYC7c1PfN0',
    appId: '1:890102022489:web:9eba0bc8942699aa4d8c48',
    messagingSenderId: '890102022489',
    projectId: 'testesp8266-1427e',
    authDomain: 'testesp8266-1427e.firebaseapp.com',
    databaseURL: 'https://testesp8266-1427e-default-rtdb.firebaseio.com',
    storageBucket: 'testesp8266-1427e.appspot.com',
    measurementId: 'G-EKBKTTS2PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcqLzv93UsPcqRe3iKrm-mmxnKWPQYbIk',
    appId: '1:890102022489:android:0feedb80136715184d8c48',
    messagingSenderId: '890102022489',
    projectId: 'testesp8266-1427e',
    databaseURL: 'https://testesp8266-1427e-default-rtdb.firebaseio.com',
    storageBucket: 'testesp8266-1427e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb1DM0TiY6n0TmY14he1QHvN3fm_Zv2Gk',
    appId: '1:890102022489:ios:2697a88f0a51d0cd4d8c48',
    messagingSenderId: '890102022489',
    projectId: 'testesp8266-1427e',
    databaseURL: 'https://testesp8266-1427e-default-rtdb.firebaseio.com',
    storageBucket: 'testesp8266-1427e.appspot.com',
    iosBundleId: 'com.example.remoteHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBMNgAMcy0TVMr4VNnq_08DxYC7c1PfN0',
    appId: '1:890102022489:web:2937ddd0fcdcc6f84d8c48',
    messagingSenderId: '890102022489',
    projectId: 'testesp8266-1427e',
    authDomain: 'testesp8266-1427e.firebaseapp.com',
    databaseURL: 'https://testesp8266-1427e-default-rtdb.firebaseio.com',
    storageBucket: 'testesp8266-1427e.appspot.com',
    measurementId: 'G-4V1VR2GYZ0',
  );

}